### ISSUE TITLE
Different objects for Delegates

### ISSUE THREAD

**Issue by vanniktech** [sockeqwe/AdapterDelegates#14] opened 2016-04-10 09:23 UTC
Hey there ;) I tried using this library for the following RecyclerView scheme and found it a bit cumbersome to work with it. The scheme basically looks like this:

Custom Widget (No data needed)
Divider (No data needed)
Header (String needed)
Member 1 (Member needed)
Member 2 (Member needed)
Member 3 (Member needed)
...
Member X (Member needed)
Add Member Button (No data needed)
Divider (No data needed)
Simple View displayed (No data needed)
Divider (No data needed)
Header with right button (Strings needed)
Nested View (Data needed (List<Data))

Via the Add Member it's possible to add members. If you have added members there will be shown another Divider and Layout underneath the Add Member button.

Also for every view type that has `No data needed`, `createView` would be enough since I won't be doing anything in `onBindViewHolder`. I just want to inflate my layout and show it.

I could try to put everything in one List of type `Object` and then create some `Divider` and `Header` objects since I'd need something to satisfy the `isForViewType` method but I'm really against `List<Object` as it's error prone.

It might also be that this type of RecyclerView scheme is just too complex. Any ideas?

**Comment by sockeqwe** [comment] 2016-04-10 15:40
Hi there,
well, how would you implement something like this directly in RecyclerView Adapter without this library. I'm pretty sure that you can map this solution to a solution that uses this library.

The solution I can think of are similar to the ones you already have suggested:
1) Create / generate a `List<Item>` that is already in that order so that it is easy for your adapter to display them. What I'm talking about is introducing some "dummy" classes that don't have data per se, but are just in the `List<Item>` to make it easier (and less error prone) to deal with ViewHolder (with or without this library). Something like this:
```java
interface Item {}

class CustomWidget implements Item {}
class Member implements Item { ... }
class AddMemberButton implement Item {}
class SimpleView implements Item {}
class Divider implements Item {} 
class HeaderRightButton implements Item{}
class NestedThing implements Item {}
```

and then you pass a `List<Item>` to your adapter and build `AdapterDelegates` like this:

```java
class CustomWidget extends AbsListItemAdapterDelegate<CustomWidget, Item, CustomWidgetViewHolder>

 @Override public boolean isForViewType(Item item, List<Item> items, int position) {
    return item instanceof CustomWidget;
  }

  @Override public CustomWidgetViewHolder onCreateViewHolder(ViewGroup parent) {
    return new CustomWidgetViewHolder(...);
  }

  @Override public void onBindViewHolder(CustomWidget item, CatViewHolder vh) {
    // Not needed?
  }
}
```
etc.

One could also use `List<Object>` instead of `List<Item>` ... I guess it's a personal preference to have a little bit more type safety with the disadvantage of an empty interface `Item`.

2) Alternative: one could use RecyclerView ItemDecorators i.e. for dividers. From my understanding you want to avoid having a `List<Item>` as shown in first approach, but rather having `List<Member>`, right?
So one could do something like this:

```java
class MyAdapter extends ListDelegationAdapter<List<Member>> {
    
   @Override
   public void getItemCount(){
      return items.size() + 1 +1 ... ; // +1 for Custom Widget, +1 for  each non Member item
   }
}
```

```java
class CustomWidget extends AbsListItemAdapterDelegate<CustomWidget, Item, CustomWidgetViewHolder>

 @Override public boolean isForViewType(Item item, List<Item> items, int position) {
    return position == 0;
  }

  @Override public CustomWidgetViewHolder onCreateViewHolder(ViewGroup parent) {
    return new CustomWidgetViewHolder(...);
  }

  @Override public void onBindViewHolder(CustomWidget item, CatViewHolder vh) {
    // Not needed?
  }
}
```

Would that be a solution or do you have a concrete solution I could integrate in version 2.0 of this library?

**Comment by vanniktech** [comment] 2016-04-11 21:19
Thanks for the detailed response. Yeah the `interface Item` approach is doable though again it requires a lot of work and also in the case of `Member` I'm just using the Model object and I don't want to let it implement an interface from the UI. So basically I'd have to wrap the Model object in a wrapper let the wrapper implement the interface. Not very cool either.

As for the `Not needed` what do you think of an `EmptyBindViewAbsListItemAdapterDelegate` which basically has the `onBindViewHolder` method implemented and does nothing? The other methods you should go an implement in any case since they require a meaningful return statement.

`RecyclerView ItemDecorators` unfortunately do not work there since the dividers are not always shown and sometimes they should be merged and I already simplified the example above. So I thought it's best to just create a View for dividers and use that.

Also the headers were not yet taken into account. There's also a way to implement that cleanly.

Not necessarily only `List<Member>`, there might also be a `List<Invitation>` (depending on whether users are invited or not) though there we show all of them in one layout rather than in one layout per dataset as for the member case. So in that case from my understanding `class MyAdapter extends ListDelegationAdapter<List<Member>> {` does not quite work. Some more generic type other than `List<Member>` would again though but then we're back to problem number 1.

The thing that I also don't necessarily like in the example of `CustomWidget` is that the class knows that it's for the position 0 and only for that. What if I might want to reuse that Delegate for another RecyclerView and there it'll be displayed as the last item?

Concrete solution, not really, I just wrote the things together and basically did my own little system though it's not yet fully reusable. Maybe we'll find something together that works for 2.0 ;)

**Comment by sockeqwe** [comment] 2016-04-12 10:58
>  I'm just using the Model object and I don't want to let it implement an interface from the UI

I see two solutions: Use a PresentationModel (perfect addition if you already have an MVP based app) or `List<Object>`

> `EmptyBindViewAbsListItemAdapterDelegate` which basically has the onBindViewHolder method implemented and does nothing? 

Will never be part of the library. This is something if needed should be implemented by the user of the library.

> Not necessarily only List<Member>, there might also be a List<Invitation> (depending on whether users are invited or not) though there we show all of them in one layout rather than in one layout per dataset as for the member case. So in that case from my understanding class MyAdapter extends ListDelegationAdapter<List<Member>> { does not quite work. Some more generic type other than List<Member> would again though but then we're back to problem number 1.

The problem is the underlying data structure `List<>` used by the adapter. Since java is strongly typed you have to introduce a common super type (like `Item` interface) for both `Member` and `Invitation`.
Again, in MVP, letting the Presenter build a `List<Item>` from a mixed list of `Member`, `Invitation`, `CustomWidget`, `Divider` etc. is by far the cleanest and best solution to this problem.
If that for whatever reason doesn't work for you, the only thing you can do is using `List<Object>`. So again, the problem is not AdapterDelegates library. The problem is that java is strongly typed and therefore requires `List<Something>` to be able to compile without errors.

An alternative is to work with two lists in your adapter. For simplicity, Llet's focus on `Member` and `Invitation` (and ignore `CustomWidget`, `CustomWidget ` etc. for now)

```java
class Adapter {
    List<Member> members;
    List<Invitation> invitations;

   @Override
    public int getItemsCount(){
      return members.size() + invitations.size():
   }
}
```

So now it's up to you to specify which `AdapterDelegate` should be used on which position and since RecyclerView is index based we have to provide some kind of mapping from an index (position) to an item from `List<Member>` or `List<Invitation>`.
But before we go further, we still have the problem of type safety, since `AdapterDelegatesManager<Something>`and `AdapterDelegate<Something>` also requires a type. But what is that `Something`. Again, we could give a damn on type safety and simply use `Object`. However, there is another way. You might have noticed that `ListDelegationAdapter<T extends List<?>> extends AbsDelegationAdapter<T>`. So this library doesn't force you to use a List as datasource for your Adapter.
So you could build a datasource structure which is not a List per se, like this:

```java
class MyDatasource {
   List<Member> members;
   List<Invitation> invitations;

  public int size(){
     return members.size() + invitations.size();
  }
  
  // could be improved with Generic Methods instead of Object as return type
  public Object get(int position) {
     if (position < members.size() -1){
        return members.get(position);
     } else {
        return invitations.get(position - members.size() );
     }
  }
}
```

So basically this `MyDatasource` is the object that is responsible to do the "mapping" of index to an object which is required since RecyclerView is index based.

```java
class MemberAdapterDelegate extends AbsAdapterDelegate<MyDatasourece> {

   @Override
    public boolean isForViewType(MyDatasource items, int position){
         return items.get(position) instanceof Member;
     }
}
```

But at the end it turns out that `MyDatasource` is kind of facade which actually implements quite a similar API as `List` does. So why not use `List` directly. I know you don't want your model classes implement a UI related common super type (like `Item` interface), but then I strongly recommend to have a look into MVP and PresentationModel because for me that is the better and less error prone solution.

The more I think about your problem, the more I come to the conclusion that it is a problem of the adapters datasource / dataset structure (which is out of scope of this library) and once you have found a datasource structure that fits your needs AdapterDelegates can be used for that kind of issues. This is already doable since version 1.0 of this library and from my point of view nothing we should change or address in AdapterDelegates 2.0.

Don't you agree?

**Comment by vanniktech** [comment] 2016-04-12 16:04
Yeah I totally agree that MVP is really good and a clean way to achieve those things. Unfortunately in reality it's not always easy to integrate these concepts into an app where there's no architecture at all and you have time constraints. I like the trick with `AbsAdapterDelegate<MyDatasourece>` though. I'll look further into that.

Yup I agree now that this is more a problem on my side rather than on the library. In any case thank you for taking your time and for this library. I also enjoyed the article to it :+1:

**Comment by sockeqwe** [comment] 2016-04-12 16:44
>  Unfortunately in reality it's not always easy to integrate these concepts into an app 

I disagree, bad code slows you down much much much more.

>  I like the trick with AbsAdapterDelegate<MyDatasourece> though.

I recommend to use `List`. You can build a List (PresentationModel) also without MVP.

Thanks for your feedback.

**Closed by sockeqwe** 2016-04-12 16:44 UTC
